name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: Compile resume pdf
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: thomasweise/docker-texlive-full:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            cd data
            pdflatex sofia_domracheva_resume.tex
      - name: Generate PNG preview
        run: |
            sudo apt-get update
            sudo apt-get install -y poppler-utils
            pdftoppm -png -r 300 -f 1 -l 1 sofia_domracheva_resume.pdf resume_preview
            mv resume_preview-1.png resume_preview.png
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply pdflatex changes
